// sync action types
const LOGIN = 'LOGIN';
const REGISTRATION = 'REGISTRATION';
const LOGOUT = 'LOGOUT';
const SET_INCIDENTS = 'SET_INCIDENTS';
const SET_USERS = 'SET_USERS';
const CHANGE_ASSIGNEE_USER_ID = 'CHANGE_ASSIGNEE_USER_ID';
const CLOSE_MODAL = 'CLOSE_MODAL';

// async action types
const POST_LOGIN = 'POST_LOGIN';
const POST_REGISTRATION = 'POST_REGISTRATION';
const GET_INCIDENTS = 'GET_INCIDENTS';
const GET_USERS = 'GET_USERS';
const CREATE_INCIDENT = 'CREATE_INCIDENT';
const DELETE_INCIDENT = 'DELETE_INCIDENT';

export {
    POST_LOGIN,
    LOGIN,
    LOGOUT,
    POST_REGISTRATION,
    REGISTRATION,
    GET_INCIDENTS,
    SET_INCIDENTS,
    GET_USERS,
    SET_USERS,
    CHANGE_ASSIGNEE_USER_ID,
    CREATE_INCIDENT,
    CLOSE_MODAL,
    DELETE_INCIDENT
}