// sync action types
const LOGIN = 'LOGIN';
const REGISTRATION = 'REGISTRATION';
const LOGOUT = 'LOGOUT';
const SET_INCIDENTS = 'SET_INCIDENTS';
const GET_USERS = 'GET_USERS';
const CHANGE_ASSIGNEE_USER_ID = 'CHANGE_ASSIGNEE_USER_ID';

// async action types
const GET_INCIDENTS = 'GET_INCIDENTS';
const POST_LOGIN = 'POST_LOGIN';

export {
    POST_LOGIN,
    LOGIN,
    REGISTRATION,
    LOGOUT,
    GET_INCIDENTS,
    SET_INCIDENTS,
    GET_USERS,
    CHANGE_ASSIGNEE_USER_ID,
}