const LOGIN = 'LOGIN';
const REGISTRATION = 'REGISTRATION';
const LOGOUT = 'LOGOUT';
const GET_INCIDENTS = 'GET_INCIDENTS';
const GET_USERS = 'GET_USERS';
const CHANGE_ASSIGNEE_USER_ID = 'CHANGE_ASSIGNEE_USER_ID';

export {
    LOGIN,
    REGISTRATION,
    LOGOUT,
    GET_INCIDENTS,
    GET_USERS,
    CHANGE_ASSIGNEE_USER_ID,
}