// sync action types
const LOGIN = 'LOGIN';
const REGISTRATION = 'REGISTRATION';
const LOGOUT = 'LOGOUT';
const SET_INCIDENTS = 'SET_INCIDENTS';
const SET_USERS = 'SET_USERS';
const CHANGE_ASSIGNEE_USER_ID = 'CHANGE_ASSIGNEE_USER_ID';
const CLOSE_MODAL = 'CLOSE_MODAL';
const UPDATE_VALUES_CREATE_INCIDENT_FORM = 'UPDATE_VALUES_CREATE_INCIDENT_FORM';
const UPDATE_VALUES_LOGIN_FORM = 'UPDATE_VALUES_LOGIN_FORM';
const UPDATE_VALUES_REGISTRATION_FORM = 'UPDATE_VALUES_REGISTRATION_FORM';
const RESET_CREATE_INCIDENT_FORM = 'RESET_CREATE_INCIDENT_FORM';
const SET_DATA_FOR_UPDATING = 'SET_DATA_FOR_UPDATING';
const RESET_REGISTRATION_FORM = 'RESET_REGISTRATION_FORM';
const UPDATE_LOADER = 'UPDATE_LOADER';
const CHANGE_ACTION_WITH_LIST_OF_INCIDENTS =
    'CHANGE_ACTION_WITH_LIST_OF_INCIDENTS';

// async action types
const POST_LOGIN = 'POST_LOGIN';
const POST_REGISTRATION = 'POST_REGISTRATION';
const GET_INCIDENTS = 'GET_INCIDENTS';
const GET_USERS = 'GET_USERS';
const CREATE_INCIDENT = 'CREATE_INCIDENT';
const DELETE_INCIDENT = 'DELETE_INCIDENT';
const UPDATE_INCIDENT = 'UPDATE_INCIDENT';
const CHANGE_KEY_DEPS_ON_PATH = 'CHANGE_KEY_DEPS_ON_PATH';

export {
    POST_LOGIN,
    LOGIN,
    LOGOUT,
    POST_REGISTRATION,
    REGISTRATION,
    GET_INCIDENTS,
    SET_INCIDENTS,
    GET_USERS,
    SET_USERS,
    CHANGE_ASSIGNEE_USER_ID,
    CREATE_INCIDENT,
    CLOSE_MODAL,
    DELETE_INCIDENT,
    UPDATE_VALUES_CREATE_INCIDENT_FORM,
    UPDATE_VALUES_LOGIN_FORM,
    UPDATE_VALUES_REGISTRATION_FORM,
    UPDATE_INCIDENT,
    SET_DATA_FOR_UPDATING,
    RESET_CREATE_INCIDENT_FORM,
    RESET_REGISTRATION_FORM,
    CHANGE_KEY_DEPS_ON_PATH,
    UPDATE_LOADER,
    CHANGE_ACTION_WITH_LIST_OF_INCIDENTS
};
